### ISSUE TITLE
Trouble for box_read() with JSON files

### ISSUE THREAD

**Issue by nathancday** [brendan-r/boxr#86]
I noticed the JSON related tests failing for me locally and traced the error back to `rio::import()`. Would like to confirm with someone else though....

This code is lifted from `test_05`:

```
  # Write a little .json file
  tf <- paste0(tempfile(), ".json")
  df <- data.frame(a = letters[1:5], b = 1:5, c = round(rnorm(5), 3), 
                   stringsAsFactors = FALSE)
  l  <- list(a = 1:10, b = matrix(1, 3, 3), c = df)
```

And it `l` looks like this:

```
l
$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1

$c
  a b      c
1 a 1  0.824
2 b 2 -0.575
3 c 3  0.448
4 d 4 -1.343
5 e 5  0.187
```

A nice three element list. But when we upload to Box and get the intermediate function `rio::import()` involved things get ugly. According to the `rio` docs `import()` "only ever returns a single data frame", and this is seems to be the root of the problem.

```
b <- box_ul(0, tf)
l2 <- box_read(b$id)
# normal read in message
l2
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
In addition: Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

You can't even view the object due to the error in matching names.

You can get a viable (but gross) object if you adjust the `simplifyDataFrame = ` argument that is passed through to the `jsonlite::fromJSON()` call happening within `rio::import()`

```
l3 <- box_read(b$id, simplifyDataFrame = FALSE)
l3
    a  b.1  b.2  b.3            c
1   1    1    1    1 a, 1, -0.643
2   2    1    1    1 b, 2, -2.318
3   3    1    1    1  c, 3, 0.244
4   4 <NA> <NA> <NA>  d, 4, -1.01
5   5 <NA> <NA> <NA>  e, 5, 0.186
6   6 <NA> <NA> <NA>         <NA>
7   7 <NA> <NA> <NA>         <NA>
8   8 <NA> <NA> <NA>         <NA>
9   9 <NA> <NA> <NA>         <NA>
10 10 <NA> <NA> <NA>         <NA>
```

While this is view-able, it doesn't represent the original data well and would require additional cleaning steps by the end-user.

To prove this problem is coming from `rio::import()`, we get the same error if we go directly.

```
rio::import(tf)
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
In addition: Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```
Even the rio prescribed alternative `import_list()` fails with the same error.

IMO I think the logic should be adjusted for `box_read()` so that it will bypass `rio` altogether for JSON formats and just call `jsonlite::fromJSON()` directly. Which will return the original object properly.

```
jsonlite::fromJSON(tf)
$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1

$c
  a b      c
1 a 1 -0.643
2 b 2 -2.318
3 c 3  0.244
4 d 4 -1.010
5 e 5  0.186
```

This shouldn't interfere with any of the Box API logic, since the file is already downloaded locally via `boxr:::boxGet()` before reading it into R with `rio::import()`.

**Comment by ijlyttle** [comment]
Hmmm...

How do the following calls work for you?

```r
box_read_json("foo.json")
```

```r
box_read("foo.json", read.fun = jsonlite::fromJSON)
```

**Comment by nathancday** [comment]
`box_read_json()` gives me the same Error about names not matching as above.

But the `box_read(...., read_fun = jsonlite::fromJSON)` give me the expect output (3 element list).

Are you seeing the same thing?

**Comment by ijlyttle** [comment]
I have not tried it yet, but I think using the `read_fun` might be the best way to go in the short term.

Have you used the function `purrr::partial()`? This could be a useful tool here, as well. 

My thought, for now, would be to look at `box_read_json()` to see it how it might be doing things differently than `box_read(...., read_fun = jsonlite::fromJSON)`.

**Comment by nathancday** [comment]
Looks like the `boxr_read_{specific}` functions are relying on the `format` argument instead of `read_fun` for prescribing the read-in function. That leaves them open the to the decisions of `rio::import()`, which is the source of this data frame mash-up behavior.

What do you think about shifting all of the group to `boxr_read_spec(read_fun = "spec::read_spec", ...)`  instead? That seems like it would work, and should keep these functions agnostic of `rio`

Let me know if you can reproduce it first.

**Comment by ijlyttle** [comment]
I tried your example from above, but I don't see the same thing as you. One thing that may be different is how we are writing the temp file. I don't see an instruction from you, but I use:

```r
jsonlite::write_json(l, tf)
```

How about for you?

**Comment by nathancday** [comment]
Sorry I should have started off with a `reprex`.

``` r
library(rio)
library(jsonlite)
library(boxr)
#> Reading client id from .Renviron
#> Reading client secret from .Renviron
#> boxr: Authenticated at box.com as Nathan C Day (nathancday@gmail.com)
#> Welcome to boxr 0.3.4.99999!
#> Bug reports & Getting Help: https://github.com/brendan-R/boxr/issues

tf <- paste0(tempfile(), ".json")

df <- data.frame(a = letters[1:5], b = 1:5, c = round(rnorm(5), 3), 
                 stringsAsFactors = FALSE)
l  <- list(a = 1:10, b = matrix(1, 3, 3), c = df)

# writeLines(jsonlite::write_json(l, tf) # BoxR test
write_json(l, tf)

rio::import(tf)
#> Warning in format.data.frame(x, digits = digits, na.encode = FALSE):
#> corrupt data frame: columns will be truncated or padded with NAs
#> Error in match.names(clabs, names(xi)): names do not match previous names
jsonlite::fromJSON(tf)
#> $a
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> 
#> $b
#>      [,1] [,2] [,3]
#> [1,]    1    1    1
#> [2,]    1    1    1
#> [3,]    1    1    1
#> 
#> $c
#>   a b     c
#> 1 a 1 0.560
#> 2 b 2 1.600
#> 3 c 3 0.731
#> 4 d 4 1.016
#> 5 e 5 0.395
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by nathancday** [comment]
Sorry I was half asleep for the last comment 😴. Here is a more complete reprex. With the uploads and downloads.

``` r
library(rio)
library(jsonlite)
library(boxr) # auth-ing on attach
#> Reading client id from .Renviron
#> Reading client secret from .Renviron
#> boxr: Authenticated at box.com as Nathan C Day (nathancday@gmail.com)
#> Welcome to boxr 0.3.4.99999!
#> Bug reports & Getting Help: https://github.com/brendan-R/boxr/issues

tf <- paste0(tempfile(), ".json")

df <- data.frame(a = letters[1:5], b = 1:5, c = round(rnorm(5), 3), 
                 stringsAsFactors = FALSE)
l  <- list(a = 1:10, b = matrix(1, 3, 3), c = df)

# writeLines(jsonlite::write_json(l, tf) # BoxR test
write_json(l, tf)

rio::import(tf)
#> Warning in format.data.frame(x, digits = digits, na.encode = FALSE):
#> corrupt data frame: columns will be truncated or padded with NAs
#> Error in match.names(clabs, names(xi)): names do not match previous names
jsonlite::fromJSON(tf)
#> $a
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> 
#> $b
#>      [,1] [,2] [,3]
#> [1,]    1    1    1
#> [2,]    1    1    1
#> [3,]    1    1    1
#> 
#> $c
#>   a b      c
#> 1 a 1  0.376
#> 2 b 2 -0.053
#> 3 c 3 -0.317
#> 4 d 4  1.236
#> 5 e 5 -0.232

b <- box_ul(0, tf)
#> 
  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |=================================================================| 100%

box_read(b$id)
#> Remote file '/var/folders/09/fpsmqczx5sb6t4v1b66tv7tm0000gp/T//RtmpqOtc7g/fileb6f02bdc4cab.json' read into memory as an object of class data.frame
#> Warning in format.data.frame(x, digits = digits, na.encode = FALSE):
#> corrupt data frame: columns will be truncated or padded with NAs
#> Error in match.names(clabs, names(xi)): names do not match previous names
box_read(b$id, format = "json")
#> Remote file '/var/folders/09/fpsmqczx5sb6t4v1b66tv7tm0000gp/T//RtmpqOtc7g/fileb6f02bdc4cab.json' read into memory as an object of class data.frame
#> Warning in format.data.frame(x, digits = digits, na.encode = FALSE):
#> corrupt data frame: columns will be truncated or padded with NAs
#> Error in match.names(clabs, names(xi)): names do not match previous names
box_read(b$id, read_fun = fromJSON)
#> Remote file '/var/folders/09/fpsmqczx5sb6t4v1b66tv7tm0000gp/T//RtmpqOtc7g/fileb6f02bdc4cab.json' read into memory as an object of class list
#> $a
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> 
#> $b
#>      [,1] [,2] [,3]
#> [1,]    1    1    1
#> [2,]    1    1    1
#> [3,]    1    1    1
#> 
#> $c
#>   a b      c
#> 1 a 1  0.376
#> 2 b 2 -0.053
#> 3 c 3 -0.317
#> 4 d 4  1.236
#> 5 e 5 -0.232
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ijlyttle** [comment]
Hey Nathan - just a quick note that I have not forgotten about this - things are a bit crazy for my now, so I beg your patience.

**Comment by nathancday** [comment]
No worries at all on my end. That's why I wanted to help out in the first place. Take your time and enjoy the holidays, no rush!

**Comment by nathancday** [comment]
The more I think of this, I think this is really a `rio` design choice. I opened up at parallel issue at Rio https://github.com/leeper/rio/issues/199 about this, but that is focused on `rio::import_list()`. 

The `box_read_json()` function will work as expected if there is just a single data frame in JSON, which feels reasonable, to me. Would it make sense to just add an example to the docs for a list of data frames showing the workaround pattern, `box_read(box_id, read_fun = jsonlite::readJSON)`, and consider this closed. We would still have to update the tests somehow to reflect.

**Comment by nathancday** [comment]
This should be resolved now, with the GitHub version of `rio` in https://github.com/leeper/rio/pull/200

**Comment by ijlyttle** [comment]
I am getting the same problem, even using the dev version of rio.

I have changed `box_read_json()` so that it defaults to `jsonlite::fromJSON()` - the test for `box_read_json()` works again.

I am thinking to change `box_read()` so that it calls `box_read_json()` if it detects a `.json` extension.

**Comment by nathancday** [comment]
hmm I passing the JSON tests here with leeper/rio@93d6387

**Comment by ijlyttle** [comment]
For me, with [leeper/rio@93d6387](https://github.com/leeper/rio/commit/93d6387) installed, I am still getting a `data.frame` returned from `box_read()`.

**Comment by nathancday** [comment]
maybe it's another package or namespace clash does `rio::import()` work for you like this?

``` r
# from boxR/test_05
tf <- paste0(tempfile(), ".json")
df <- data.frame(a = letters[1:5], b = 1:5, c = round(rnorm(5), 3), 
                 stringsAsFactors = FALSE)
l  <- list(a = 1:10, b = matrix(1, 3, 3), c = df)

writeLines(jsonlite::toJSON(l), tf)

rio::import(tf)
#> $a
#>  [1]  1  2  3  4  5  6  7  8  9 10
#> 
#> $b
#>      [,1] [,2] [,3]
#> [1,]    1    1    1
#> [2,]    1    1    1
#> [3,]    1    1    1
#> 
#> $c
#>   a b      c
#> 1 a 1 -0.821
#> 2 b 2 -0.171
#> 3 c 3 -1.662
#> 4 d 4  0.082
#> 5 e 5  1.293
```

<sup>Created on 2019-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       macOS Mojave 10.14          
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2019-02-23                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib
#>  assertthat    0.2.0      2017-04-11 [2]
#>  backports     1.1.3      2018-12-14 [1]
#>  callr         3.1.1      2018-12-21 [1]
#>  cellranger    1.1.0      2016-07-27 [2]
#>  cli           1.0.1      2018-09-25 [1]
#>  crayon        1.3.4      2019-01-24 [1]
#>  curl          3.3        2019-01-10 [1]
#>  data.table    1.12.0     2019-01-13 [1]
#>  desc          1.2.0      2018-05-01 [2]
#>  devtools      2.0.1      2018-10-26 [1]
#>  digest        0.6.18     2018-10-10 [1]
#>  evaluate      0.12       2018-10-09 [1]
#>  forcats       0.4.0      2019-02-17 [1]
#>  foreign       0.8-71     2018-07-20 [1]
#>  fs            1.2.6      2018-08-23 [1]
#>  glue          1.3.0      2018-07-17 [2]
#>  haven         2.1.0      2019-02-19 [1]
#>  hms           0.4.2      2018-03-10 [2]
#>  htmltools     0.3.6      2017-04-28 [2]
#>  jsonlite      1.6        2018-12-07 [1]
#>  knitr         1.20       2018-02-20 [2]
#>  magrittr      1.5        2014-11-22 [1]
#>  memoise       1.1.0      2017-04-21 [2]
#>  openxlsx      4.1.1      2019-02-22 [1]
#>  pillar        1.3.1      2018-12-15 [1]
#>  pkgbuild      1.0.2      2018-10-16 [1]
#>  pkgconfig     2.0.2      2018-08-16 [1]
#>  pkgload       1.0.2      2018-10-29 [1]
#>  prettyunits   1.0.2      2015-07-13 [2]
#>  processx      3.2.1      2018-12-05 [1]
#>  ps            1.3.0      2018-12-21 [1]
#>  R6            2.4.0      2019-02-14 [1]
#>  Rcpp          1.0.0      2018-11-07 [1]
#>  readxl        1.3.0      2019-02-15 [1]
#>  remotes       2.0.2      2018-10-30 [1]
#>  rio           0.5.18     2019-02-23 [1]
#>  rlang         0.3.1      2019-01-08 [1]
#>  rmarkdown     1.10       2018-06-11 [2]
#>  rprojroot     1.3-2      2018-01-03 [2]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.3.1      2019-02-13 [1]
#>  stringr       1.4.0      2019-02-10 [1]
#>  testthat      2.0.1      2018-10-13 [1]
#>  tibble        2.0.1      2019-01-12 [1]
#>  usethis       1.4.0      2018-08-14 [1]
#>  withr         2.1.2.9000 2018-10-18 [1]
#>  yaml          2.2.0      2018-07-25 [1]
#>  zip           1.0.0      2017-04-25 [2]
#>  source                             
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  Github (r-lib/crayon@74bee76)      
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  Github (awalker89/openxlsx@ead0038)
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  Github (leeper/rio@93d6387)        
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  Github (jimhester/withr@be57595)   
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#> 
#> [1] /Users/nathanday/Library/R/3.5/library
#> [2] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

</details>

**Comment by ijlyttle** [comment]
I guess I needed to restart my session, then the JSON tests worked, thanks! 

I have added a "remote" for rio so that our dev version will get the rio dev version; implying that rio will have to go to CRAN before us. It's in my branch - when I PR into the main repository, I'll re-close the issue.

I am still not passing the "versions" test - but I suspect the problem is elsewhere.

**Comment by ijlyttle** [comment]
I know this is off topic, but just to note that when I created a "new" box-app, my own, the versions tests started working again. This might be a good thing to note in a developers' guide.

**Comment by nathancday** [comment]
I know Box underwent an API overhaul in the last ~1-2 years, I wonder if that cryptic error was due to the old boxR account's app being created under the old API?

**Comment by ijlyttle** [comment]
🤔

**Comment by ijlyttle** [comment]
closed in #94
